github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    
image:
  file: .gitpod.Dockerfile
checkoutLocation: gitpod-k3s  
ports:
  - port: 4040 # pyspark UI
    onOpen: notify
    
tasks:
  - name: K3S (QEMU)
    command: |
      /opt/qemu-k3s/qemu.sh
  - name: Main
    command: |
      source /opt/qemu-k3s/ws-init.sh
  - name: setup
    init: |
      export SPARK_HOME=/opt/spark
      echo "export SPARK_HOME=/opt/spark" > $HOME/.bashrc
      clear
vscode:
  extensions:
    - ms-python.python
