output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "ecr_repo" {
  description = "Container registry repo URL"
  value       = aws_ecr_repository.registry.repository_url
}

output "iam_secret_key" {
  description = <<EOM
    The IAM secret key, which you provide when configuring the AWS CLI.
  EOM
  value       = aws_iam_access_key.iam_secret_key.id
}

output "iam_secret_access_key" {
  description = <<EOM
    The PGP encrypted IAM secret access key.
    To decrypt: terraform output -raw iam_secret_access_key
    | base64 --decode | keybase pgp decrypt
  EOM
  value       = aws_iam_access_key.iam_secret_key.encrypted_secret
}
